language: c
sudo: required
before_install:
    - YARAV=$(curl -L -s -k https://github.com/VirusTotal/yara/releases/latest | grep -oP "\d+\.\d+\.\d+" | head -1)
    - wget https://github.com/VirusTotal/yara/archive/v$(echo $YARAV).tar.gz -O ../yara.tar.gz
    - tar -xzvf ../yara.tar.gz -C ..
    - cd ../yara-$(echo $YARAV)
    - ./bootstrap.sh
    - ./configure
    - make
    - sudo make install
    - sudo ldconfig
    - cd -
script:
    - echo "test" > testfile
    - FAIL=0
    - for i in $(ls -d */); do for j in $(find $i -type f -regex ".*\.yara?"); do echo $j; yara $j testfile; if [[ $? -ne 0 ]]; then FAIL=1; fi; done; done
    - exit $FAIL


